import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Providers from "./providers";
import Footer from "@/components/Footer";
import Hero from "@/components/Hero";

// Заменяем Geist на Inter (ближайший стандартный аналог SF Pro Text)
// Для использования настоящего SF Pro Text нужна лицензия или загрузка через @next/font
const inter = Inter({
  variable: "--font-sf-pro-text",
  subsets: ["latin"],
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} antialiased`}
        style={{ fontFamily: 'var(--font-sf-pro-text), system-ui, sans-serif' }}
      >
        <Providers>
          <Header/>
          <Hero/>
          {children}
          <Footer/>
        </Providers>
      </body>
    </html>
  );
}